name: Add a new member when issue raised
on:
  issues:
    types:  ["opened"]

# Declare default permissions as read only.
permissions: read-all

jobs:
  add-member:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Is add member issue?
        id: is_add
        run: |
          if [[ ${{ github.event.issue.title }} == "Please add me as a member of the redhat-cop organization" ]]; then
            echo "member=1" >> $GITHUB_OUTPUT
          fi  

      - name: Added member to config.yml
        if: steps.is_add.outputs.member == 1
        uses: mikefarah/yq@f15500b20a1c991c8729870ba60a4dc3524b6a94 # v4.44.2
        with:
          cmd: yq -i '.orgs.redhat-cop.members += "${{ github.event.issue.actor.login }}"' config.yaml

      - name: Lowercase and sort config.yaml key and values
        if: steps.is_add.outputs.member == 1
        uses: mikefarah/yq@f15500b20a1c991c8729870ba60a4dc3524b6a94 # v4.44.2
        with:
          cmd: yq -i e '(... | select(type == "!!seq"))[] |= downcase' config.yaml && yq -i e '(... | select(type == "!!seq")) |= sort' config.yaml && yq -i 'sort_keys(..)' config.yaml

      - name: changed?
        run: |
          cat config.yaml